replicaCount: 1
labels:
  app: counter-app

container:
  port: 5000

image:
  repository: galhalevi/counter-app
  tag: "1.2"

service:
  type: NodePort
  port: 80

configMap:
  data:
    COUNTER_PATH: "/data/counter.txt"

secret:
  adminToken: "super-duper-secret"

cronjob:
  enabled: true
  schedule: "* * * * *" # every minute