apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-counter.fullname" . }}-secret
  labels:
    {{ include "flask-counter.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_TOKEN: {{ .Values.secret.adminToken | b64enc | quote }}