apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-counter.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "flask-counter.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http